### ISSUE TITLE
Not Autoresponsive for Height

### ISSUE THREAD

**Issue by jayesbe** [xudafeng/autoresponsive-react-native#4]
In the samples and examples provided.. the Height is being manually set. 

Can Height be automatic based on the contents and the grid responsive to width.

I don't know the height of the contents since the contents are dynamic.

**Comment by xudafeng** [comment]
xudafeng/autoresponsive-react#33

**Comment by jayesbe** [comment]
I was able to do something using onLayout. Though the solution wasn't perfect and all the content was floating on top of each other.. it wasn't auto-responsive.

**Comment by m0ngr31** [comment]
Can you explain how you would do this on RN? I've been fighting it for a bit now and I can't find a good way to accomplish it. I looked at the other issue that was linked, but how do I pre-render something in RN?

**Comment by florianbepunkt** [comment]
I would also be interested in this… I assume most use cases (except using pure images) involves text or some other dynamic height content.

**Comment by florianbepunkt** [comment]
alright. found a solution… if anyone else stumble across the same problem, please have a look at this gist: https://gist.github.com/florianbepunkt/da81926461ddf42441b0bb3b2fa4429f

basically we use an onLayout method for each rendered child and store the calculated height of our dynamic content in an array that we feed back as the height in the same child's style object.

not sure if this is super performant though as onLayout gets called multiple times so unsure how this behaves with larges lists.
